window.noname_update={
    version:'1.9.0',
    changeLog:[
        '增加乱斗模式',
        '塔防、炉石、对决模式改进',
        '显示时间选项',
        '历史记录栏',
        '自定义背景音乐',
        '触屏手势改进',
        '素材管理',
        '新皮肤',
    ],
    files:{
        global:[
            'game/game.js',
        ],
    }
}
